const loc2labels = {
    'Northern Europe' : '5d383691e3aeaa3b57419751',
    'Central Europe' : '5d383691e3aeaa3b5741974d',
    'Baltics' : '5d383691e3aeaa3b5741974d',
    'Russia' : '5d383691e3aeaa3b5741974d',
    'Southern Europe' : '5d383691e3aeaa3b57419753',
    'North America' : '62754e583967c467c029e2a9',
    'Middle East' : '5d383691e3aeaa3b5741974f',
    'Africa' : '5d383691e3aeaa3b5741974f',
    'Asia' : '5d7faa0995587922dc09ae7d',
    'Oceania' : '5d7faa0995587922dc09ae7d',
    'Australia' : '5d7faa0995587922dc09ae7d',
    'South America' : '5d383691e3aeaa3b5741974b'
}

const country2locs = {
    'Albania' : 'Central Europe',
    'Armenia' : 'Central Europe',
    'Australia' : 'Australia',
    'Austria' : 'Northern Europe',
    'Azerbaijan' : 'Central Europe',
    'Belarus' : 'Russia',
    'Belgium' : 'Northern Europe',
    'Bulgaria' : 'Central Europe',
    'Canada' : 'North America',
    'Croatia' : 'Central Europe',
    'Cyprus' : 'Southern Europe',
    'Czech Republic' : 'Central Europe',
    'Denmark' : 'Northern Europe',
    'Estonia' : 'Baltics',
    'Finland' : 'Northern Europe',
    'France' : 'Southern Europe',
    'Germany' : 'Northern Europe',
    'Greece' : 'Southern Europe',
    'Hungary' : 'Central Europe',
    'India' : 'Asia',
    'Ireland' : 'Northern Europe',
    'Israel' : 'Middle East',
    'Italy' : 'Southern Europe',
    'Latvia' : 'Baltics',
    'Lithuania' : 'Baltics',
    'Ireland' : 'Northern Europe',
    'Luxembourg' : 'Northern Europe',
    'Moldavia' : 'Central Europe',
    'Norway' : 'Northern Europe',
    'Netherlands' : 'Northern Europe',
    'Norway' : 'Northern Europe',
    'Portugal' : 'Southern Europe',
    'Romania' : 'Central Europe',
    'Serbia' : 'Central Europe',
    'Slovakia' : 'Central Europe',
    'Slovenia' : 'Central Europe',
    'Spain' : 'Southern Europe',
    'Sweden' : 'Northern Europe',
    'Switzerland' : 'Northern Europe',
    'Turkey' : 'Middle East',
    'United Kingdom' : 'Northern Europe',
    'USA' : 'North America'
}